- name: Download and install wp
  get_url:
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wp.tar.gz
    force=yes

- name: Extract wp files
  unarchive:
    src=/tmp/wp.tar.gz
    dest=/tmp/
    copy=no

- name: Remove existing /var/www/html directory
  file:
    path: /var/www/html
    state: absent

- name: Rename worpress directory
  command: mv /tmp/wordpress /var/www/html

- name: update wp-config file
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php

- name: Change www directory ownership to ec2-user and set permissions
  command: find /var/www -type d -exec sudo chmod 2775 {} \;
  notify:
    - Restart apache
