  - name: Provisioning EC2 instances
    ec2:
      region: us-east-1 
      key_name: demowebservers
      instance_type: t2.micro
      image: ami-467ca739
      wait: yes
      group: webservers
      count: 1
      vpc_subnet_id: subnet-8fa56cd2
      assign_public_ip: yes
      instance_tags: '{"cms":"wordpress", "type":"webserver"}'
    register: ec2

  - name: Create host group
    add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
    with_items: "{{ ec2.instances }}"

  - name: Wait for instances to come up
    wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
    with_items: "{{ ec2.instances }}"
